### ISSUE TITLE
how to solve the problem?

### ISSUE THREAD

**Issue by croll7** [upowai/wallet#1]
root@rig950A10:/wallet# pip3 install -r requirements.txt                                                                                                                
Collecting asttokens==2.4.1                                                                                                                                             
  Using cached asttokens-2.4.1-py2.py3-none-any.whl (27 kB)                                                                                                             
Collecting base58==0.2.5                                                                                                                                                
  Using cached base58-0.2.5-py3-none-any.whl (4.1 kB)                                                                                                                   
Collecting certifi==2023.11.17                                                                                                                                          
  Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)                                                                                                             
Collecting charset-normalizer==2.0.12                                                                                                                                   
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)                                                                                                       
Collecting colorama==0.4.6                                                                                                                                              
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)                                                                                                              
Collecting executing==2.0.1                                                                                                                                             
  Using cached executing-2.0.1-py2.py3-none-any.whl (24 kB)                                                                                                             
Collecting fastecdsa==2.3.0                                                                                                                                             
  Using cached fastecdsa-2.3.0.tar.gz (49 kB)                                                                                                                           
  Installing build dependencies ... done                                                                                                                                
  Getting requirements to build wheel ... done                                                                                                                          
  Installing backend dependencies ... done                                                                                                                              
  Preparing metadata (pyproject.toml) ... done                                                                                                                          
  WARNING: Generating metadata for package fastecdsa produced metadata for project name unknown. Fix your #egg=fastecdsa fragments.
Discarding https://files.pythonhosted.org/packages/b1/da/c87a9e1a489d1c4f408309ea6704e125f2cbba9110eac07071f6e1b3b4bb/fastecdsa-2.3.0.tar.gz#sha256=6c59aba650862a59f601
ff7f66cd6712f4798ae68907c953d58417a5887103de (from https://pypi.org/simple/fastecdsa/) (requires-python:>=3.7): Requested unknown from https://files.pythonhosted.org/pa
ckages/b1/da/c87a9e1a489d1c4f408309ea6704e125f2cbba9110eac07071f6e1b3b4bb/fastecdsa-2.3.0.tar.gz#sha256=6c59aba650862a59f601ff7f66cd6712f4798ae68907c953d58417a5887103de
 (from -r requirements.txt (line 7)) has inconsistent name: filename has 'fastecdsa', but metadata has 'unknown'
ERROR: Could not find a version that satisfies the requirement fastecdsa==2.3.0 (from versions: 1.0.0b1, 1.0.1b1, 1.0.1b2, 1.0.1b3, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1
.1.2, 1.1.3, 1.2.1, 1.3.1, 1.3.2, 1.4.1, 1.4.2, 1.4.3, 1.5.1, 1.5.2, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 2.0.0, 2.1.0, 2.1.1, 2
.1.2, 2.1.3, 2.1.4, 2.1.5, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2)
ERROR: No matching distribution found for fastecdsa==2.3.0

**Comment by upowai** [comment]
Set up a virtual environment. Start by executing the command `sudo apt install python3.10-venv`. After the installation is complete, navigate to the wallet directory by entering `cd wallet`. Once you're in the wallet directory, initiate the creation of a virtual environment by running `python3.10 -m venv myvenv`. To activate the virtual environment, use the command `source myvenv/bin/activate`. With the virtual environment activated, you can proceed to install the required packages by running `pip install -r requirements.txt`.
